format = """
[](Yellow)\
$username\
$directory\
$git_branch\
$docker_context\
$time\
[ ](bg:Blue fg:Yellow)\
[](fg:Blue)\
"""

# symbols: https://www.nerdfonts.com/cheat-sheet

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:Yellow fg:Black"
style_root = "bg:Yellow fg:Red"
format = """\
[ $user ]($style)\
[](fg:Yellow bg:Blue )\
"""

[username.substitutions]
"jonat" = "Z☻llinger"
"Administrator" = "ɹǝƃuıʃʃoZ"

[directory]
style = "bg:Blue fg:White"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "♪~ ᕕ(ᐛ)ᕗ/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
style = "bg:Blue fg:White"
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = "ಠ⌣ಠ "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "


[docker_context]
style = "bg:Blue fg:White"
symbol = " "
format = "[ $symbol ]($style)"

[git_branch]
style = "bg:Blue fg:Yellow"
symbol = " "
format = """
[]($style)\
[ on $symbol $branch ](fg:#Black bg:Yellow)\
[ ]($style)\
"""


[memory_usage]
style = "bg:Blue fg:White"
symbol = " "
format = "[ $symbol ]($style)"

[python]
style = "bg:Blue fg:White"
symbol = " "
format = "[ $symbol ]($style)"
